### PR TITLE
feat: mcap storage impl

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by jhurliman** [comment]
@wep21 I've been working on this as well, and I hit a wall with the mcap library dependencies. Since it is a header-only library, any project that depends on it (such as `rosbag2_storage_mcap`) needs to be able to find the headers for all of the dependencies and link against those libraries. Specifically: libfmt, libcrypto++, libzstd, liblz4.

Some options:

1. Remove the mcap_vendor project and merge it into rosbag2_storage_mcap. All of the conan cmake directives in mcap_vendor/CMakeLists.txt would merge into rosbag2_storage_mcap.
2. Convert the upstream mcap library from header-only to a static library. This is the approach I started on and it seems to be working, but I don't know if it is preferable over option 1 or not.

**Comment by jhurliman** [comment]
https://github.com/foxglove/mcap/pull/279 is merged which should simplify things in this repo. I can put together a PR soon based on the work here.

**Comment by wep21** [comment]
@jhurliman @emersonknapp I moved fetchcontent into rosbag2_storage_mcap directly and fixed ci error.

**Review by jhurliman — APPROVED** [review]

**Comment by jhurliman** [comment]
@wep21 great! I'm going to merge this and start hooking up the API calls.

**Pull request merged**
