### PR TITLE
Some minor improvements in rosbag2_storage_mcap after review

### PR DESCRIPTION
**Pull request by MichaelOrlov**
Some minor improvements in `rosbag2_storage_mcap` after review.
Better latter than never :smile: 

1. Fixed some findings from Clang-Tidy
1. Some renames according to the ROS2 coding style
1. Add default initialization for member variables
1. Moved code responsible for adding schema and channel from `write(msg)` to `create_topic(topic)` method to reduce performance burden on first message write and in lieu to preparation for moving schema collection process to upper `SequentialWriter` layer.

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

### CODE REVIEW

**Comment by emersonknapp** [comment]
Is `clang-tidy` enabled as an automated linter? I wouldn't block tidying if not, but we also can't expect/force future contributions to follow those guidelines if they aren't automatically tested.

**Review by emersonknapp — APPROVED** [review]
LGTM adding schema+channel on `create_topic` rather than in `write`. 

If I read correctly, this removes one `schema_ids.find()` per `write`? That's probably a mild performance improvement on many-topic files.

**Comment by MichaelOrlov** [comment]
Yes. mild to minor. I was more concern that when we start writing on first message we had to find and prepare this schema and channel information and **write** it to storage. It's more significant impact on performance rather than one search for schema.

**Comment by MichaelOrlov** [comment]
@emersonknapp As regards:
> Is clang-tidy enabled as an automated linter? I wouldn't block tidying if not, but we also can't expect/force future contributions to follow those guidelines if they aren't automatically tested.

No, clang-tidy is not enabled by default and not all its warnings make sense to address.
Clang-Tidy built-in in CLion IDE and I have a hefty highlights with suggestions how to fix warnings. 
I fixed most of them which are really could be a problems or make sense to fix.

I don't expect that further contribution will be compliant with Clang-Tidy. It's just good to have such fixes time to time or during code review.

**Pull request merged**
