### PR TITLE
Add mcap vendor

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by wep21** [comment]
FYI @emersonknapp @jhurliman

**Comment by jhurliman** [comment]
@wep21  I have a prototype roscap tool for ROS1, it's a fork of rosbag that swaps out the .bag v2.0 format for mcap. It required a few fixes for linking against system libraries that I assume will be helpful for the ros2 storage plugin as well. https://github.com/foxglove/mcap/pull/238 just merged, so I would recommend using commit hash 95a5373441b369a40bcce123e93180919de05e90 for the foxglove/mcap repo.

EDIT: After trying this out on a few different systems, I think I need to take a different approach with the mcap C++ library. Linking against system libraries is a non-starter, the libfmt version that ships in Ubuntu 18.04 looks nothing like the latest release and the ZSTD API I'm using requires `ZSTD_STATIC_LINKING_ONLY`. I think the next step is to vendor these packages directly into the mcap repo and come up with a CMake-based build that statically links in the dependencies.

**Comment by wep21** [comment]
@jhurliman https://github.com/ros-tooling/rosbag2_storage_mcap/pull/2 is a implementation using conan.cmake instead of creating the vendor packages for dependencies. How about this?

**Comment by jhurliman** [comment]
@wep21 that looks great!

**Comment by emersonknapp** [comment]
I think I agree that the version that doesn't require 2 extra vendor packages does look a lot nicer. Less is more :)

**Pull request closed without merging**
