### PR TITLE
feat: add play impl

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by wep21** [comment]
@jtbandes @jhurliman I found out the error as below occurs when reading mcap.
```
❯ ros2 bag play rosbag2_2022_03_14-13_32_21/rosbag2_2022_03_14-13_32_21_0.mcap -s mcap
pure virtual method called
terminate called without an active exception
fish: Job 1, 'ros2 bag play rosbag2_2022_03_1…' terminated by signal SIGABRT (Abort)
```
https://github.com/foxglove/mcap/blob/e79355a9e99efd5094b15f21bb361a85d9e748bc/cpp/mcap/include/mcap/reader.inl#L197
Do you know how to solve it?

**Comment by jtbandes** [comment]
So far I haven't been able to reproduce your `pure virtual method called` error. However, I did find a dangling reference issue caused by [this line](https://github.com/foxglove/mcap/blob/5a3c884a34ebe68127d434667973662f674c873d/cpp/mcap/include/mcap/reader.inl#L1312) (`message` is a reference to a temporary variable created [here](https://github.com/foxglove/mcap/blob/5a3c884a34ebe68127d434667973662f674c873d/cpp/mcap/include/mcap/reader.inl#L975) so it should not outlive the lambda call). Filed a ticket: https://github.com/foxglove/mcap/issues/295

**Comment by wep21** [comment]
@jtbandes Updating mcap seems to solve the problem.
Now #10 blocks this.
```
❯ ros2 bag play rosbag2_2022_03_15-16_36_24/ -s mcap
seek() is not implemented.
```

**Comment by jtbandes** [comment]
After updating this branch I got your `pure virtual method called` error. I think it is not really a pure virtual method being called, but a memory corruption error similar to the other one. I'm still investigating.

**Comment by jtbandes** [comment]
@wep21 I changed the serialization_format to use the Channel's `messageEncoding` instead of the Schema's `encoding` which should be more correct and doesn't require a conversion. However, when I tried to test this with `ros2 bag [record/play/info]`, it doesn't seem like the code is being executed. Do you know how to test this `get_metadata` method properly?

**Review by jhurliman — APPROVED** [review]

**Pull request merged**
